services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    depends_on:
      api:
        condition: service_healthy
        restart: false
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /frontend
          ignore: 
          - node_modules/
        - action: rebuild
          path: ./frontend/Dockerfile
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./docker-compose.yml
  api:
    build:
      context: ./api/
    environment:
      - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./api/dbs:/api/dbs:z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/healthcheck"]
      interval: 2s
      timeout: 5s
      retries: 10
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /api
          ignore: 
          - __pycache__/
        - action: rebuild
          path: ./api/Dockerfile
        - action: rebuild
          path: ./api/requirments.txt
        - action: rebuild
          path: ./docker-compose.yml
